Numpy Crash vourse

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

Creating numpy arrays

In [5]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [6]:
data

array([[[0.26210918, 0.43239634, 0.28790771, 0.35036385],
        [0.08072438, 0.05780537, 0.13111131, 0.75847196],
        [0.23193291, 0.78757934, 0.07603581, 0.14841163]],

       [[0.57699124, 0.64295155, 0.41515994, 0.91722337],
        [0.36418517, 0.35227364, 0.50534952, 0.49440837],
        [0.86307259, 0.06252014, 0.47010546, 0.45550043]]])

In [7]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [11]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

Reading numpy arrays

In [12]:
# attributes
shape = data.shape
size = data.size
types = data.dtype

In [13]:
data

array([[[0.26210918, 0.43239634, 0.28790771, 0.35036385],
        [0.08072438, 0.05780537, 0.13111131, 0.75847196],
        [0.23193291, 0.78757934, 0.07603581, 0.14841163]],

       [[0.57699124, 0.64295155, 0.41515994, 0.91722337],
        [0.36418517, 0.35227364, 0.50534952, 0.49440837],
        [0.86307259, 0.06252014, 0.47010546, 0.45550043]]])

In [14]:
shape

(2, 3, 4)

In [15]:
size

24

In [16]:
types

dtype('float64')

In [17]:
# slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singlevalue = data[0][0][0]


In [18]:
data

array([[[0.59234691, 0.74447543, 0.89923102, 0.42694387],
        [0.99300819, 0.38915934, 0.18347702, 0.21214766],
        [0.81811142, 0.41588789, 0.18107095, 0.4294157 ]],

       [[0.46634377, 0.41782907, 0.15486075, 0.1314768 ],
        [0.76346266, 0.55439537, 0.26416551, 0.39813704],
        [0.8027832 , 0.43774014, 0.9996918 , 0.55184913]]])

In [19]:
arr

array([[0.59234691, 0.74447543, 0.89923102, 0.42694387],
       [0.99300819, 0.38915934, 0.18347702, 0.21214766],
       [0.81811142, 0.41588789, 0.18107095, 0.4294157 ]])

In [20]:
slicer

array([[0.59234691, 0.74447543, 0.89923102, 0.42694387],
       [0.99300819, 0.38915934, 0.18347702, 0.21214766]])

In [21]:
reverse

array([[0.46634377, 0.41782907, 0.15486075, 0.1314768 ],
       [0.76346266, 0.55439537, 0.26416551, 0.39813704],
       [0.8027832 , 0.43774014, 0.9996918 , 0.55184913]])

In [22]:
singlevalue

np.float64(0.5923469141958234)

Update

In [14]:
list = np.random.rand(10)
list2 = np.random.rand(10)

In [ ]:
# basic math 
add = np.add(list,list2)
sub = np.subtract(list,list2)
div = np.divide(list,list2)
mult = np.multiply(list,list2)
dot = np.dot(list,list2)

In [ ]:
# stat functions

sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = ([2,3])
mins = np.min(list)
maxs = np.max(list)

In [15]:
data

array([[[0.26210918, 0.43239634, 0.28790771, 0.35036385],
        [0.08072438, 0.05780537, 0.13111131, 0.75847196],
        [0.23193291, 0.78757934, 0.07603581, 0.14841163]],

       [[0.57699124, 0.64295155, 0.41515994, 0.91722337],
        [0.36418517, 0.35227364, 0.50534952, 0.49440837],
        [0.86307259, 0.06252014, 0.47010546, 0.45550043]]])

In [16]:
data[0][0][0] = 70

In [18]:
data[0][0][0]

np.float64(70.0)

In [19]:
data.sort()
data

array([[[2.87907713e-01, 3.50363854e-01, 4.32396337e-01, 7.00000000e+01],
        [5.78053746e-02, 8.07243793e-02, 1.31111312e-01, 7.58471962e-01],
        [7.60358107e-02, 1.48411626e-01, 2.31932911e-01, 7.87579343e-01]],

       [[4.15159944e-01, 5.76991237e-01, 6.42951552e-01, 9.17223374e-01],
        [3.52273635e-01, 3.64185173e-01, 4.94408369e-01, 5.05349524e-01],
        [6.25201351e-02, 4.55500434e-01, 4.70105459e-01, 8.63072586e-01]]])

In [20]:
print(data.shape)

(2, 3, 4)


In [22]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [26]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)
test = np.insert(zeroes, 2 ,4)
print (test)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]
[0. 0. 4. 0. 0. 0. 0. 0. 0. 3. 4.]


Delete

In [27]:
data

array([[[2.87907713e-01, 3.50363854e-01, 4.32396337e-01, 7.00000000e+01,
         5.78053746e-02, 8.07243793e-02],
        [1.31111312e-01, 7.58471962e-01, 7.60358107e-02, 1.48411626e-01,
         2.31932911e-01, 7.87579343e-01]],

       [[4.15159944e-01, 5.76991237e-01, 6.42951552e-01, 9.17223374e-01,
         3.52273635e-01, 3.64185173e-01],
        [4.94408369e-01, 5.05349524e-01, 6.25201351e-02, 4.55500434e-01,
         4.70105459e-01, 8.63072586e-01]]])

In [28]:
np.delete(data, 0, axis=1)

array([[[0.13111131, 0.75847196, 0.07603581, 0.14841163, 0.23193291,
         0.78757934]],

       [[0.49440837, 0.50534952, 0.06252014, 0.45550043, 0.47010546,
         0.86307259]]])

In [30]:
np.save("new array", data)

In [32]:
test = np.load("new array.npy")

In [33]:
test

array([[[2.87907713e-01, 3.50363854e-01, 4.32396337e-01, 7.00000000e+01,
         5.78053746e-02, 8.07243793e-02],
        [1.31111312e-01, 7.58471962e-01, 7.60358107e-02, 1.48411626e-01,
         2.31932911e-01, 7.87579343e-01]],

       [[4.15159944e-01, 5.76991237e-01, 6.42951552e-01, 9.17223374e-01,
         3.52273635e-01, 3.64185173e-01],
        [4.94408369e-01, 5.05349524e-01, 6.25201351e-02, 4.55500434e-01,
         4.70105459e-01, 8.63072586e-01]]])